[package]
name = "rich-markdown-pbcopy"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.54", features = ["derive"] }
clipboard-rs = "0.3.1"
markdown = "1.0.0"
ureq = "3.1.4"
